eureka:
  instance:
    preferIpAddress: true
  client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  profiles:
    active: default
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  type-aliases-package: com.fang.lincensingservicemysql.model
logging:
  level:
    com.fang: info
    com.netflix: WARN
    org.springframework.web: WARN
    org.mybatis:  info


