eureka:
  instance:
    preferIpAddress: true
  client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.wangfang: debug
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
  #Setting logging levels
